"use client";

import { useEffect, useState } from "react";
import { getBranches } from "@/lib/public-api";
import BranchList from "@/components/shared/BranchList";
import { useLang } from "@/contexts/LanguageContext";
import { Building2 } from "lucide-react";

const sampleBranches = [
  {
    id: 1,
    name: "Kamaladi Head Office",
    nameNp: "कमलादी प्रमुख कार्यालय",
    address: "Reliance Bhawan, Kamaladi, Kathmandu",
    addressNp: "रिलायन्स भवन, कमलादी, काठमाडौं",
    province: "Bagmati",
    district: "Kathmandu",
    localBody: "Kathmandu Metro-01",
    phone: "+977-01-5361104",
    email: "info@reliancenepal.com.np",
    latitude: 27.7088,
    longitude: 85.318,
    region: "head-office",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM, Fri: 10:00 AM - 3:00 PM",
    managerName: "Chief Executive Officer",
  },
  {
    id: 2,
    name: "New Road Branch",
    nameNp: "न्यू रोड शाखा",
    address: "New Road, Kathmandu-22",
    addressNp: "न्यू रोड, काठमाडौं-२२",
    province: "Bagmati",
    district: "Kathmandu",
    localBody: "Kathmandu Metro",
    phone: "01-5345104",
    email: "newroad@reliancenepal.com.np",
    latitude: 27.7008,
    longitude: 85.3127,
    region: "inside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Subash K.C.",
  },
  {
    id: 3,
    name: "Imadol Branch",
    nameNp: "इमाडोल शाखा",
    address: "Imadol, Mahalaxmi-1, Lalitpur",
    addressNp: "इमाडोल, महालक्ष्मी-१, ललितपुर",
    province: "Bagmati",
    district: "Lalitpur",
    localBody: "Mahalaxmi Municipality",
    phone: "01-5201704",
    email: "imadol@reliancenepal.com.np",
    latitude: 27.656,
    longitude: 85.3286,
    region: "inside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Saraswoti Shrestha",
  },
  {
    id: 4,
    name: "Sitapaila Branch",
    nameNp: "सीतापाइला शाखा",
    address: "Nagarjun-4, Sitapaila, Kathmandu",
    addressNp: "नागार्जुन-४, सीतापाइला, काठमाडौं",
    province: "Bagmati",
    district: "Kathmandu",
    localBody: "Nagarjun Municipality",
    phone: "01-5233397",
    email: "sitapaila@reliancenepal.com.np",
    latitude: 27.7108,
    longitude: 85.2872,
    region: "inside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Sagar Shahi",
  },
  {
    id: 5,
    name: "Pokhara Branch",
    nameNp: "पोखरा शाखा",
    address: "New Road, Pokhara-4, Kaski",
    addressNp: "न्यू रोड, पोखरा-४, कास्की",
    province: "Gandaki",
    district: "Kaski",
    localBody: "Pokhara Metropolitan",
    phone: "061-580983",
    email: "pokhara@reliancenepal.com.np",
    latitude: 28.232,
    longitude: 83.9857,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Santosh Khaniya",
  },
  {
    id: 6,
    name: "Butwal Branch",
    nameNp: "बुटवल शाखा",
    address: "Traffic Chowk, Butwal-6, Rupandehi",
    addressNp: "ट्राफिक चोक, बुटवल-६, रुपन्देही",
    province: "Lumbini",
    district: "Rupandehi",
    localBody: "Butwal Sub-Metropolitan",
    phone: "071-590174",
    email: "butwal@reliancenepal.com.np",
    latitude: 27.7,
    longitude: 83.4667,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Laxman Neupane",
  },
  {
    id: 7,
    name: "Narayangarh Branch",
    nameNp: "नारायणगढ शाखा",
    address: "Shahid Chowk, Bharatpur-1, Chitwan",
    addressNp: "शहीद चोक, भरतपुर-१, चितवन",
    province: "Bagmati",
    district: "Chitwan",
    localBody: "Bharatpur Metropolitan",
    phone: "056-596598",
    email: "narayangarh@reliancenepal.com.np",
    latitude: 27.6833,
    longitude: 84.4333,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Satish Maharjan",
  },
  {
    id: 8,
    name: "Kohalpur Branch",
    nameNp: "कोहलपुर शाखा",
    address: "NTV Road, Kohalpur-11, Banke",
    addressNp: "एनटीभी रोड, कोहलपुर-११, बाँके",
    province: "Lumbini",
    district: "Banke",
    localBody: "Kohalpur Municipality",
    phone: "081-542154",
    email: "kohalpur@reliancenepal.com.np",
    latitude: 28.2167,
    longitude: 81.6833,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Sushil Basnet",
  },
  {
    id: 9,
    name: "Besishahar Branch",
    nameNp: "बेसीशहर शाखा",
    address: "Manange Chok, Besisahar-8, Lamjung",
    addressNp: "मनाङ्गे चोक, बेसीशहर-८, लमजुङ",
    province: "Gandaki",
    district: "Lamjung",
    localBody: "Besishahar Municipality",
    phone: "066-520815",
    email: "besishahar@reliancenepal.com.np",
    latitude: 28.243,
    longitude: 84.386,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Bharat Nepali",
  },
  {
    id: 10,
    name: "Banepa Branch (Janagal)",
    nameNp: "बनेपा शाखा (जनागाल)",
    address: "Janagal, Banepa-7, Kavrepalanchowk",
    addressNp: "जनागाल, बनेपा-७, काभ्रेपलाञ्चोक",
    province: "Bagmati",
    district: "Kavrepalanchok",
    localBody: "Banepa Municipality",
    phone: "011-663244",
    email: "banepa@reliancenepal.com.np",
    latitude: 27.6303,
    longitude: 85.522,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Manish Taujale",
  },
  {
    id: 11,
    name: "Dhadingbesi Branch",
    nameNp: "धादिङबेसी शाखा",
    address: "Nilkantha Municipality, Dhadingbesi",
    addressNp: "नीलकण्ठ नगरपालिका, धादिङबेसी",
    province: "Bagmati",
    district: "Dhading",
    localBody: "Nilakantha Municipality",
    phone: "010-590707",
    email: "dhadingbesi@reliancenepal.com.np",
    latitude: 27.8333,
    longitude: 84.8333,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Prakash Kumar Shrestha",
  },
  {
    id: 12,
    name: "Charali Branch",
    nameNp: "चारआली शाखा",
    address: "Mechinagar-13, Charali, Jhapa",
    addressNp: "मेचीनगर-१३, चारआली, झापा",
    province: "Koshi",
    district: "Jhapa",
    localBody: "Mechinagar Municipality",
    phone: "023-461102",
    email: "charali@reliancenepal.com.np",
    latitude: 26.633,
    longitude: 87.833,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Amod Kumar Gupta",
  },
  {
    id: 13,
    name: "Dhangadhi Branch",
    nameNp: "धनगढी शाखा",
    address: "Main Road, Dhangadhi-4, Kailali",
    addressNp: "मुख्य सडक, धनगढी-४, कैलाली",
    province: "Sudurpashchim",
    district: "Kailali",
    localBody: "Dhangadhi Sub-Metropolitan",
    phone: "091-523462",
    email: "dhangadhi@reliancenepal.com.np",
    latitude: 28.7,
    longitude: 80.5833,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Doban Bahadur Rawal",
  },
  {
    id: 14,
    name: "Birtamod Branch",
    nameNp: "बिर्तामोड शाखा",
    address: "Mukti Chowk, Birtamod-5, Jhapa",
    addressNp: "मुक्ति चोक, बिर्तामोड-५, झापा",
    province: "Koshi",
    district: "Jhapa",
    localBody: "Birtamod Municipality",
    phone: "023-530743",
    email: "birtamod@reliancenepal.com.np",
    latitude: 26.6333,
    longitude: 87.9,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Jiban Shrestha",
  },
  {
    id: 15,
    name: "Damak Branch",
    nameNp: "दमक शाखा",
    address: "Ganesh Man Chok, Damak-6, Jhapa",
    addressNp: "गणेशमान चोक, दमक-६, झापा",
    province: "Koshi",
    district: "Jhapa",
    localBody: "Damak Municipality",
    phone: "023-572602",
    email: "damak@reliancenepal.com.np",
    latitude: 26.65,
    longitude: 87.6833,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Ishahak Rai",
  },
  {
    id: 16,
    name: "Attariya Branch",
    nameNp: "अत्तरिया शाखा",
    address: "Godawari-1, Attariya, Kailali",
    addressNp: "गोदावरी-१, अत्तरिया, कैलाली",
    province: "Sudurpashchim",
    district: "Kailali",
    localBody: "Godawari Municipality",
    phone: "091-550033",
    email: "attariya@reliancenepal.com.np",
    latitude: 28.8167,
    longitude: 80.5667,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Mahesh Bahadur Kunwar",
  },
  {
    id: 17,
    name: "Mahendranagar Branch",
    nameNp: "महेन्द्रनगर शाखा",
    address: "Mandi Gali, Bhimdatta-4, Kanchanpur",
    addressNp: "मण्डी गल्ली, भिमदत्त-४, कञ्चनपुर",
    province: "Sudurpashchim",
    district: "Kanchanpur",
    localBody: "Bhimdatta Municipality",
    phone: "099-520440",
    email: "mahendranagar@reliancenepal.com.np",
    latitude: 28.9667,
    longitude: 80.2,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Mahesh Prasad Bhatt",
  },
  {
    id: 18,
    name: "Surkhet Branch",
    nameNp: "सुर्खेत शाखा",
    address: "Birendranagar-6, Surkhet",
    addressNp: "वीरेन्द्रनगर-६, सुर्खेत",
    province: "Karnali",
    district: "Surkhet",
    localBody: "Birendranagar Municipality",
    phone: "083-591485",
    email: "surkhet@reliancenepal.com.np",
    latitude: 28.5833,
    longitude: 81.6333,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Manish Sedhain",
  },
  {
    id: 19,
    name: "Bhairahawa Branch",
    nameNp: "भैरहवा शाखा",
    address: "Bank Road, Siddharthanagar-12, Rupandehi",
    addressNp: "बैंक रोड, सिद्धार्थनगर-१२, रुपन्देही",
    province: "Lumbini",
    district: "Rupandehi",
    localBody: "Siddharthanagar Municipality",
    phone: "071-590901",
    email: "bhairahawa@reliancenepal.com.np",
    latitude: 27.5,
    longitude: 83.45,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Pragyan Poudel",
  },
  {
    id: 20,
    name: "Tandi Branch",
    nameNp: "टाँडी शाखा",
    address: "Ratnanagar-2, Tandi, Chitwan",
    addressNp: "रत्ननगर-२, टाँडी, चितवन",
    province: "Bagmati",
    district: "Chitwan",
    localBody: "Ratnanagar Municipality",
    phone: "056-593269",
    email: "tandi@reliancenepal.com.np",
    latitude: 27.6333,
    longitude: 84.5167,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Narayan Wagle",
  },
  {
    id: 21,
    name: "Manigram Branch",
    nameNp: "मनिग्राम शाखा",
    address: "Tilottama-5, Manigram, Rupandehi",
    addressNp: "तिलोत्तमा-५, मनिग्राम, रुपन्देही",
    province: "Lumbini",
    district: "Rupandehi",
    localBody: "Tilottama Municipality",
    phone: "071-562902",
    email: "manigram@reliancenepal.com.np",
    latitude: 27.473,
    longitude: 83.45,
    region: "outside-valley",
    bankingHours: "Sun-Thu: 10:00 AM - 5:00 PM",
    managerName: "Ganesh Bhusal",
  },
];

export default function LangBranchesPage() {
  const lang = useLang();
  const isNp = lang === "np";
  const [branches, setBranches] = useState<any[]>(sampleBranches);

  useEffect(() => {
    getBranches()
      .then((res: any) => {
        if (Array.isArray(res) && res.length > 0) {
          setBranches(res);
        }
      })
      .catch(() => {});
  }, []);

  return (
    <>
      <section className="bg-gradient-to-br from-primary-900 via-primary-800 to-primary-950 py-14 text-white">
        <div className="container-page">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-secondary-400 mb-2">
            <Building2 className="h-4 w-4 text-secondary-400" />
            <span>{isNp ? "देशभरको शाखा सञ्जाल" : "Nationwide Branch Network"}</span>
          </div>
          <h1 className="text-3xl font-bold md:text-4xl">{isNp ? "शाखाहरू र एटीएम" : "Branches & ATM Locations"}</h1>
          <p className="mt-2 text-sm leading-relaxed text-white/80 max-w-2xl">
            {isNp
              ? "नेपालका प्रमुख शहरहरूमा सञ्चालित रिलायन्स फाइनान्सका २१ वटा शाखाहरू र एटीएम सेवाहरू पत्ता लगाउनुहोस्।"
              : "Discover Reliance Finance's 21 modern branch offices and ATM locations across Nepal."}
          </p>
        </div>
      </section>
      <section className="py-12">
        <div className="container-page">
          <BranchList branches={branches} lang={lang} />
        </div>
      </section>
    </>
  );
}
