export const redirects: Record<string, string> = {
  "/index": "/en",
  "/": "/en",

  "/introduction": "/en/about/introduction",
  "/mission-vision": "/en/about/mission-goals",
  "/framework": "/en/about/strategic-framework",
  "/timeline": "/en/about/milestones",
  "/capital": "/en/about/capital-structure",
  "/privacy": "/en/privacy-policy",

  "/deposit/normal-saving-account": "/en/products/savings/normal-saving-account",
  "/deposit/investor-saving-account": "/en/products/savings/investor-saving-account",
  "/deposit/special-saving-account": "/en/products/savings/special-saving-account",
  "/deposit/student-saving-account": "/en/products/savings/student-saving-account",
  "/deposit/shareholder-saving-account": "/en/products/savings/shareholder-saving-account",
  "/deposit/pwd-saving-account": "/en/products/savings/pwd-saving-account",
  "/deposit/dhaulagiri-saving-account": "/en/products/savings/dhaulagiri-saving-account",
  "/deposit/kanchanjunga-saving-account": "/en/products/savings/kanchanjunga-saving-account",
  "/deposit/everest-saving-account": "/en/products/savings/everest-saving-account",
  "/deposit/super-saving-account": "/en/products/savings/super-saving-account",
  "/deposit/gold-saving-account": "/en/products/savings/gold-saving-account",
  "/deposit/diamond-saving-account": "/en/products/savings/diamond-saving-account",
  "/deposit/sarathi-saving-account": "/en/products/savings/sarathi-saving-account",
  "/savings": "/en/products/savings",

  "/fixed-deposit/individual": "/en/products/fixed-deposits/individual-fixed-deposit",
  "/fixed-deposit/corporate": "/en/products/fixed-deposits/corporate-fixed-deposit",
  "/fixed-deposit/remittance": "/en/products/fixed-deposits/remittance-fixed-deposit",
  "/fixed-deposits": "/en/products/fixed-deposits",

  "/loan/agricultural": "/en/products/loans/agricultural-loan",
  "/loan/auto": "/en/products/loans/auto-loan",
  "/loan/hire-purchase": "/en/products/loans/hire-purchase-loan",
  "/loan/education": "/en/products/loans/education-loan",
  "/loan/share": "/en/products/loans/share-loan",
  "/loan/home": "/en/products/loans/home-loan",
  "/loan/fd": "/en/products/loans/fd-loan",
  "/loan/personal": "/en/products/loans/personal-loan",
  "/loan/business": "/en/products/loans/business-loan",
  "/loans": "/en/products/loans",

  "/service/mobile-banking": "/en/services/mobile-banking",
  "/service/qr-teller": "/en/services/qr-teller",
  "/service/connect-rtgs": "/en/services/connect-rtgs",
  "/service/corporatepay": "/en/services/corporatepay",
  "/service/c-asba": "/en/services/c-asba",
  "/service/debit-card": "/en/services/debit-card",
  "/service/abbs": "/en/services/abbs",
  "/service/remittance": "/en/services/remittance",
  "/service/sms-banking": "/en/services/sms-banking",
  "/service/connect-ips": "/en/services/connect-ips",
  "/service/interbank-ips": "/en/services/interbank-ips",
  "/service/ecc": "/en/services/ecc",
  "/service/disabled-friendly": "/en/services/disabled-friendly-branch",
  "/service/24-7-account-block": "/en/services/24-7-account-block",
  "/services": "/en/services",

  "/interest-rate": "/en/rates/interest-rates",
  "/base-rate": "/en/rates/base-rate-spread-rate",
  "/tariff": "/en/rates/standard-tariff-charges",
  "/forex": "/en/rates/forex-rates",
  "/rates": "/en/rates",

  "/teams/board-of-directors": "/en/governance",
  "/teams/management-team": "/en/governance",
  "/teams/head-of-department": "/en/governance",
  "/teams/branch-manager": "/en/governance",
  "/governance": "/en/governance",
  "/bod": "/en/governance",
  "/management-team": "/en/governance",
  "/hod": "/en/governance",
  "/branch-managers": "/en/governance",
  "/csr": "/en/csr",

  "/branch": "/en/branches",
  "/branches": "/en/branches",
  "/contact": "/en/contact",
  "/faq": "/en/faq",
  "/career": "/en/careers",
  "/careers": "/en/careers",
  "/gallery": "/en/gallery",
  "/downloads": "/en/downloads",
  "/emi": "/en/emi-calculator",
  "/news": "/en/publications/news",
  "/products": "/en/products",
  "/about": "/en/about",
  "/banking-hours": "/en/banking-hours",
};
